package com.epul.permispiste.metier;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonManagedReference;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Action generated by hbm2java
 */
@Entity
@Table(name = "action", catalog = "permispiste")
public class Action implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int numaction;
	private String libaction;
	private Integer scoremin;
	private List<Indicateur> indicateurs = new ArrayList<Indicateur>();
	private List<Jeu> jeux = new ArrayList<Jeu>();
	private List<Objectif> objectifs = new ArrayList<Objectif>();
	@JsonManagedReference("obtient")
	private List<Obtient> obtients = new ArrayList<Obtient>();
	private List<Regle> regles = new ArrayList<Regle>();

	public Action() {
	}

	public Action(int numaction) {
		this.numaction = numaction;
	}

	public Action(int numaction, String libaction, Integer scoremin,
			List<Indicateur> indicateurs, List<Jeu> jeux,
			List<Objectif> objectifs, List<Obtient> obtients, List<Regle> regles) {
		this.numaction = numaction;
		this.libaction = libaction;
		this.scoremin = scoremin;
		this.indicateurs = indicateurs;
		this.jeux = jeux;
		this.objectifs = objectifs;
		this.obtients = obtients;
		this.regles = regles;
	}

	@Id
	@Column(name = "NUMACTION", unique = true, nullable = false)
	public int getNumaction() {
		return this.numaction;
	}

	public void setNumaction(int numaction) {
		this.numaction = numaction;
	}

	@Column(name = "LIBACTION", length = 25)
	public String getLibaction() {
		return this.libaction;
	}

	public void setLibaction(String libaction) {
		this.libaction = libaction;
	}

	@Column(name = "SCOREMIN")
	public Integer getScoremin() {
		return this.scoremin;
	}

	public void setScoremin(Integer scoremin) {
		this.scoremin = scoremin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "action")
	@JsonManagedReference
	@JsonIgnore
	public List<Indicateur> getIndicateurs() {
		return this.indicateurs;
	}

	public void setIndicateurs(List<Indicateur> indicateurs) {
		this.indicateurs = indicateurs;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "actions")
	@JsonManagedReference
	@JsonIgnore
	public List<Jeu> getJeux() {
		return this.jeux;
	}

	public void setJeux(List<Jeu> jeux) {
		this.jeux = jeux;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "est_associe", catalog = "permispiste", joinColumns = { @JoinColumn(name = "NUMACTION", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "NUMOBJECTIF", nullable = false, updatable = false) })
	@JsonManagedReference
	@JsonIgnore
	public List<Objectif> getObjectifs() {
		return this.objectifs;
	}

	public void setObjectifs(List<Objectif> objectifs) {
		this.objectifs = objectifs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "action")
	@JsonManagedReference("obtient")
	public List<Obtient> getObtients() {
		return this.obtients;
	}

	public void setObtients(List<Obtient> obtients) {
		this.obtients = obtients;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "possede", catalog = "permispiste", joinColumns = { @JoinColumn(name = "NUMACTION", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "NUMREGLE", nullable = false, updatable = false) })
	@JsonManagedReference
	@JsonIgnore
	public List<Regle> getRegles() {
		return this.regles;
	}

	public void setRegles(List<Regle> regles) {
		this.regles = regles;
	}

}
