package com.epul.permispiste.metier;

// Generated 25 juin 2015 09:52:23 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonManagedReference;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * Apprenant generated by hbm2java
 */
@Entity
@Table(name = "apprenant", catalog = "permispiste")
public class Apprenant implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int numapprenant;
	private String nomapprenant;
	private String prenomapprenant;
	private List<Obtient> obtients = new ArrayList<Obtient>();

	public Apprenant() {
	}

	public Apprenant(int numapprenant) {
		this.numapprenant = numapprenant;
	}

	public Apprenant(int numapprenant, String nomapprenant,
			String prenomapprenant, List<Obtient> obtients) {
		this.numapprenant = numapprenant;
		this.nomapprenant = nomapprenant;
		this.prenomapprenant = prenomapprenant;
		this.obtients = obtients;
	}

	@Id
	@Column(name = "NUMAPPRENANT", unique = true, nullable = false)
	public int getNumapprenant() {
		return this.numapprenant;
	}

	public void setNumapprenant(int numapprenant) {
		this.numapprenant = numapprenant;
	}

	@Column(name = "NOMAPPRENANT", length = 25)
	public String getNomapprenant() {
		return this.nomapprenant;
	}

	public void setNomapprenant(String nomapprenant) {
		this.nomapprenant = nomapprenant;
	}

	@Column(name = "PRENOMAPPRENANT", length = 25)
	public String getPrenomapprenant() {
		return this.prenomapprenant;
	}

	public void setPrenomapprenant(String prenomapprenant) {
		this.prenomapprenant = prenomapprenant;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apprenant")
	@Cascade(value = { CascadeType.SAVE_UPDATE, CascadeType.DELETE })
	@JsonManagedReference
	public List<Obtient> getObtients() {
		return this.obtients;
	}

	public void setObtients(List<Obtient> obtients) {
		this.obtients = obtients;
	}

}
