package com.epul.permispiste.metier;

// Generated 25 juin 2015 09:52:23 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Calendrier generated by hbm2java
 */
@Entity
@Table(name = "calendrier", catalog = "permispiste")
public class Calendrier implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Date datejour;
	private List<Obtient> obtients = new ArrayList<Obtient>();

	public Calendrier() {
	}

	public Calendrier(Date datejour) {
		this.datejour = datejour;
	}

	public Calendrier(Date datejour, List<Obtient> obtients) {
		this.datejour = datejour;
		this.obtients = obtients;
	}

	@Id
	@Temporal(TemporalType.DATE)
	@Column(name = "DATEJOUR", unique = true, nullable = false, length = 10)
	public Date getDatejour() {
		return this.datejour;
	}

	public void setDatejour(Date datejour) {
		this.datejour = datejour;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "calendrier")
	public List<Obtient> getObtients() {
		return this.obtients;
	}

	public void setObtients(List<Obtient> obtients) {
		this.obtients = obtients;
	}

}
