package com.epul.permispiste.metier;

// Generated 25 juin 2015 09:52:23 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mission generated by hbm2java
 */
@Entity
@Table(name = "mission", catalog = "permispiste")
public class Mission implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int nummission;
	private Jeu jeu;
	private String libmission;
	private List<Objectif> objectifs = new ArrayList<Objectif>();

	public Mission() {
	}

	public Mission(int nummission, Jeu jeu) {
		this.nummission = nummission;
		this.jeu = jeu;
	}

	public Mission(int nummission, Jeu jeu, String libmission,
			List<Objectif> objectifs) {
		this.nummission = nummission;
		this.jeu = jeu;
		this.libmission = libmission;
		this.objectifs = objectifs;
	}

	@Id
	@Column(name = "NUMMISSION", unique = true, nullable = false)
	public int getNummission() {
		return this.nummission;
	}

	public void setNummission(int nummission) {
		this.nummission = nummission;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NUMJEU", nullable = false)
	public Jeu getJeu() {
		return this.jeu;
	}

	public void setJeu(Jeu jeu) {
		this.jeu = jeu;
	}

	@Column(name = "LIBMISSION", length = 25)
	public String getLibmission() {
		return this.libmission;
	}

	public void setLibmission(String libmission) {
		this.libmission = libmission;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "fixe", catalog = "permispiste", joinColumns = { @JoinColumn(name = "NUMMISSION", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "NUMOBJECTIF", nullable = false, updatable = false) })
	public List<Objectif> getObjectifs() {
		return this.objectifs;
	}

	public void setObjectifs(List<Objectif> objectifs) {
		this.objectifs = objectifs;
	}

}
