package com.epul.permispiste.metier;

// Generated 25 juin 2015 09:52:23 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Objectif generated by hbm2java
 */
@Entity
@Table(name = "objectif", catalog = "permispiste")
public class Objectif implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int numobjectif;
	private String libobectif;
	private List<Action> actions = new ArrayList<Action>();
	private List<Mission> missions = new ArrayList<Mission>();

	public Objectif() {
	}

	public Objectif(int numobjectif) {
		this.numobjectif = numobjectif;
	}

	public Objectif(int numobjectif, String libobectif, List<Action> actions,
			List<Mission> missions) {
		this.numobjectif = numobjectif;
		this.libobectif = libobectif;
		this.actions = actions;
		this.missions = missions;
	}

	@Id
	@Column(name = "NUMOBJECTIF", unique = true, nullable = false)
	public int getNumobjectif() {
		return this.numobjectif;
	}

	public void setNumobjectif(int numobjectif) {
		this.numobjectif = numobjectif;
	}

	@Column(name = "LIBOBECTIF", length = 25)
	public String getLibobectif() {
		return this.libobectif;
	}

	public void setLibobectif(String libobectif) {
		this.libobectif = libobectif;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "objectifs")
	public List<Action> getActions() {
		return this.actions;
	}

	public void setActions(List<Action> actions) {
		this.actions = actions;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "objectifs")
	public List<Mission> getMissions() {
		return this.missions;
	}

	public void setMissions(List<Mission> missions) {
		this.missions = missions;
	}

}
