package com.epul.permispiste.metier;

// Generated 25 juin 2015 09:52:23 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Regle generated by hbm2java
 */
@Entity
@Table(name = "regle", catalog = "permispiste")
public class Regle implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int numregle;
	private String libregle;
	private Integer scoremin;
	private List<Action> actions = new ArrayList<Action>();

	public Regle() {
	}

	public Regle(int numregle) {
		this.numregle = numregle;
	}

	public Regle(int numregle, String libregle, Integer scoremin,
			List<Action> actions) {
		this.numregle = numregle;
		this.libregle = libregle;
		this.scoremin = scoremin;
		this.actions = actions;
	}

	@Id
	@Column(name = "NUMREGLE", unique = true, nullable = false)
	public int getNumregle() {
		return this.numregle;
	}

	public void setNumregle(int numregle) {
		this.numregle = numregle;
	}

	@Column(name = "LIBREGLE", length = 25)
	public String getLibregle() {
		return this.libregle;
	}

	public void setLibregle(String libregle) {
		this.libregle = libregle;
	}

	@Column(name = "SCOREMIN")
	public Integer getScoremin() {
		return this.scoremin;
	}

	public void setScoremin(Integer scoremin) {
		this.scoremin = scoremin;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "regles")
	public List<Action> getActions() {
		return this.actions;
	}

	public void setActions(List<Action> actions) {
		this.actions = actions;
	}

}
